# https://github.com/repository-settings/app
_extends: .github
repository:
  name: zeplo-sdk
  description: A typed SDK for zeplo to avoid http calls with untyped args
  private: false
branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - Build
          - Lint
          - Test
